// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOv-c3UhhNMN9b4ELGXPVeXzu6lKpzbnQ',
    appId: '1:595964946222:web:830da23c61af3566023cbf',
    messagingSenderId: '595964946222',
    projectId: 'pet-app-c6d12',
    authDomain: 'pet-app-c6d12.firebaseapp.com',
    storageBucket: 'pet-app-c6d12.appspot.com',
    measurementId: 'G-21CGRM8LN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3q7QEZlvc7F_onlSXo5eDR579qagkMnQ',
    appId: '1:595964946222:android:429575d3afa0fa2c023cbf',
    messagingSenderId: '595964946222',
    projectId: 'pet-app-c6d12',
    storageBucket: 'pet-app-c6d12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtcEh8XHnh_PKMUru_Ay3L-i8YB38Ajcw',
    appId: '1:595964946222:ios:84554a5fc0d7d684023cbf',
    messagingSenderId: '595964946222',
    projectId: 'pet-app-c6d12',
    storageBucket: 'pet-app-c6d12.appspot.com',
    iosBundleId: 'com.example.petApp',
  );
}
